### ISSUE TITLE
11月

### ISSUE THREAD

**Issue by tiu5** [tiu5/tiu5.github.io#2]

**Comment by tiu5** [comment]
# 02
- 浏览器保存密码出现多余的自动填充，可能是使用 `form` 表单的原因，使用 `autocomplete="off"` 去禁止自动填充并不生效，不知为何
- 移动端仿原生操作可以参考前端框架 MUI
- 有空看下这个 `js` 文件：[vue-mobile-events](https://github.com/LylaYuKakola/vue-mobile-events/blob/master/E.js)

**Comment by tiu5** [comment]
# 07
- 禁止文本复制
```css
.no-touch {
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```
- vue 自定义指令
  - 传参
  - 实时更新
```js
// bind：只调用一次，指令第一次绑定到元素时调用。在这里可以进行一次性的初始化设置。
binding.arg

// 在很多时候，你可能想在 bind 和 update 时触发相同行为，而不关心其它的钩子。比如这样写:
Vue.directive('color-swatch', function (el, binding) {
  el.style.backgroundColor = binding.value
})
```
>除了 el 之外，其它参数都应该是只读的，切勿进行修改。如果需要在钩子之间共享数据，建议通过元素的 dataset 来进行。
